[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/mongodb/mongo-go-driver"
  version = "0.0.9"

[[constraint]]
  branch = "master"
  name = "github.com/globalsign/mgo"